name: 04 - Using Actions

on: 
    push

jobs:
    build:
        runs-on: ubuntu-latest
        #0. checkout code
        #1. install dependencies
        #2. execute automated tests
        defaults: 
            run:
                working-directory: 04-using-actions/action-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Unit tests
              run: npm run test
            - name: Printing Folders 
              run: ls            