name: 05 - 2 - Event Filters and Activity Types Closed

on: 
    pull_request: 
        types: 
            - closed
        branches:
            - main
    
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show description
              run: echo "Running whenever a PR is closed AND base branch is main"
