name: 10 - Controlling the Execution Flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: Whether unit tests are passing
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: Lint and Build
              run: echo "Linting and building project"
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Unit test
              run: echo "Unit testing project"
            - name: Failing tests
              if: ${{!inputs.pass-unit-tests}}
              run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            - lint-build
            - unit-test
        steps:
            - name: Deploying NonProd
              run: echo "Deploying NonProd"
    e2e-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: End to End testing
              run: echo "End to end testing"
    load-tests:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
        steps:
            - name: Load testing
              run: echo "Load testing"
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - deploy-nonprod
            - e2e-tests
            - load-tests
        steps:
            - name: Deploying to Prod
              run: echo "Deploying to prod"
