name: 13 - Using Caching

on:
    workflow_dispatch:
        inputs: 
            use-cache:
                type: boolean
                description: Whether to use caching
                default: true
            node-version:
                description: Choose node version
                type: choice
                options: 
                    - 18.x
                    - 19.x
                    - 20.x
                    - 21.x
                default:
                    20.x

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{inputs.node-version}}
            - name: Install dependencies
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploy to non-prod
              run: echo "Deploying to nonprod"
