name: 16 - Working with Environments
run-name: 16 Working with Environments | env - ${{inputs.target-env}}
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
                description: target environment

jobs:
    echo:
        environment: ${{inputs.target-env}}
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        runs-on: ubuntu-latest
        steps:
            - name: Echo vars
              run: |
                  echo "Env variable ${{env.my-env-value}}"
